### PR TITLE
Make use of path and header semantics when finding closest requests.

### PR DESCRIPTION
**Pull request by ting-yuan**
Instead of comparing request.formatted_request as strings, comparing queries in pathes and key-value pairs in headers should be semantically better and faster.

For example,
    ?current_time=10000000&important=true

would be better to match
    ?current_time=99999999&important=true

rather than
    ?current_time=1000000&important=false

This also prevents most random or time-based arguments from participating in the comparisons and makes the results more deterministic.

### CODE REVIEW

**Comment by nedn** [comment]
Please do a "git cl upload" so I can review your patch with rietveld.

**Comment by ting-yuan** [comment]
Sorry, maybe a stupid question, but would this work?
https://codereview.appspot.com/265310043/

Or should I configure the review server to which chromium uses?

**Comment by nedn** [comment]
That's fine. I will review this as soon as possible.

**Comment by nedn** [comment]
Now you can go ahead and update the version of webpagereplay in telemetry/third_party to the head :-)

**Comment by ting-yuan** [comment]
Thank you, Ned :-) Just one more question:

So I should just copy the two updated files to telemetry/third_party/webpagereplay/ and then `git cl upload` to resume the review process, right? Because telemetry/third_party/webpagereplay/ is under other git repository, there seems to be no git-style ways to cherry pick the changes?

**Comment by nedn** [comment]
Yes, there is no git style ways to cherry pick the changes. I would just rm the current webpagereplay/ folder there and replace it with the new one. Please also update the README.chromium accordingly.

**Pull request merged**
